mc : False
input_files : [
              "/data3/fmazzasc/lit_run3/DATA/pbpb/AO2D.root",
            ]
output_dir : '../lithium_results/matter/'
output_file : 'lit4_pbpb.root'
selection : 'fNSigmaTPCHe3>-2 and fNClsTPCHe3>110 and fChi2TPCHe3 > 0.5 and fAvgClusterSizeHe > 6 and fPt > 2'
is_matter : 1
