mc : False
input_files : ["/data3/fmazzasc/lit_run3/DATA/pbpb/AO2D.root"]
output_dir : '../lithium_results/clear/'
output_file : 'lit4_pbpb_data.root'
selection : 'fNSigmaTPCHe3>-2 and fNClsTPCHe3>110 and fChi2TPCHe3 > 0.5 and fAvgClusterSizeHe > 5 and fPt > 2 and 0.85<fMassTOFHad<1.05'
is_matter : 0
